# -*- coding: utf-8 -*-
"""Regression-backpropegation-scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1yaXSy_xu382gkJHzZw6xwI3weQ2hVE
"""

import pandas as pd
import numpy as np

df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

df.head()

def parameter_intitionlize(layer_dms):
  np.random.seed(3)
  parameters={}

  L=len(layer_dms)

  for i in range(1,L):

     parameters['W'+str(i)]=np.ones((layer_dms[i-1],layer_dms[1]))*0.1
     parameters['b'+str(i)]=np.zeros((layer_dms[i],1))
  return parameters

def segmoid(Z):
  A=1/(1+np.exp(-Z))
  return A

def linear_forward(A_prev,W,b):
  Z=np.dot(W.T,A_prev)+b
  A=segmoid(Z)
  return A

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

parameters=parameter_intitionlize([2,2,1])
epoche=10

for i in range(epoche):
  loss=[]
  for j in range(df.shape[0]):
    X=df[["cgpa","profile_score"]].values[j].reshape(2,1)
    Y=df[["placed"]].values[j][0]

    y_hat,A1=L_layer_forward(X,parameters)
    y_hat=y_hat[0][0]


    update_parameters(parameters,y,y_hat,A1,X)

    loss.append(-Y*np.log(y_hat) - (1-Y)*np.log(1-y_hat))


  print('Epoch - ',i+1,'Loss - ',np.array(loss).mean())

parameters

